name: 'Mirroring R-Forge to GitHub'
description: 'Mirror R-Forge repos to GitHub'
inputs:
  action:
    description: One of quick, full or cleanup
    default: quick
runs:
  using: 'docker'
  image: 'docker://runiverse/rforge-mirror'
  args:
    - ${{ inputs.action }}
