name: 'Mirroring R-Forge to GitHub'
description: 'Mirror R-Forge repos to GitHub'
inputs:
  action:
    description: One of quick, full or cleanup, or a package name
    default: quick
runs:
  using: docker
  image: docker://ghcr.io/r-universe-org/rforge-mirror
  args:
    - ${{ inputs.action }}
