name: 'Mirroring R-Forge to GitHub'
description: 'Mirror R-Forge repos to GitHub'
inputs:
  full:
    description: Perform a full mirror of all repos
    default: false
  cleanup:
    description: Delete dead r-forge repos
    default: false
runs:
  using: 'docker'
  image: 'docker://runiverse/rforge-mirror'
  args:
    - ${{ inputs.full }}
    - ${{ inputs.cleanup }}
