on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:
    inputs:
      action:
        description: Which action to perform
        required: true
        default: quick

name: Mirroring R-forge

jobs:
  update:
    name: Mirror R-forge
    runs-on: ubuntu-20.04
    steps:
      - name: Find and update R-forge repos
        uses: r-universe-org/rforge-mirror@master
        with:
          action: ${{ github.event.inputs.action }}
        env:
          GITHUB_PAT: ${{ secrets.RFORGE_PAT }}
